### ISSUE TITLE
Reasonable timeline for version deprecation

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/certification#9]
Certification program version deprecation should align with product cycles.  

Ex: Products with software on disk may be easier to update than products with software burned into silicon.

**Comment by hkamezawa** [comment]
I think that customers needs to move from old platform to new platform because of product life cycle. 
Then need to move container apps from old platform to new platform.

So,  a certification spec supported by the both of old/new platform is desirable.
I think enterprise's  product life cycle is 5 years which is aligned to server hardware life cycle.

When we set timeline as 3 years, customer needs to update certification once in its life cycle but can have a version which can cover both of new and old without trouble. So, 3-5 years will work, I think.
(*)2 years are too short for them and , of course, longer is better for them.
 
I don't want to delay the evolution of container spec, so, having "Long Term Spec version" with opinions of TOB may be an idea.

**Comment by RobDolinMS** [comment]
Proposal for addressing this is in PR #29
